SET IDENTITY_INSERT [dbo].[tblGenreMovie] ON 
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (1, 3, N'Action', 28)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (2, 3, N'Adventure', 12)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (3, 3, N'Animation', 16)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (4, 3, N'Comedy', 35)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (5, 3, N'Crime', 80)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (6, 3, N'Documentary', 99)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (7, 3, N'Drama', 18)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (8, 3, N'Family', 10751)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (9, 3, N'Fantasy', 14)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (10, 3, N'History', 36)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (11, 3, N'Horror', 27)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (12, 3, N'Music', 10402)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (13, 3, N'Mystery', 9648)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (14, 3, N'Romance', 10749)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (15, 3, N'Science Fiction', 878)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (16, 3, N'TV Movie', 10770)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (17, 3, N'Thriller', 53)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (18, 3, N'War', 10752)
INSERT [dbo].[tblGenreMovie] ([ID], [Source_Cat], [Source_Name], [Source_Id]) VALUES (19, 3, N'Western', 37)
SET IDENTITY_INSERT [dbo].[tblGenreMovie] OFF